name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    services:
      postgres:
        image: postgres:12.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: mentoring_project_server_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Setup Ruby and install gems
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2' # Not needed with a .ruby-version file
        bundler-cache: true
        working-directory: './server'
    - name: Setup test database
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: postgres
      run: |
        cd server && bin/rails db:setup
    - name: Install dependencies
      run: npm install -g yarn && yarn   
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
